#!/usr/bin/env bash

# Build script for Docker Hub automated builds

docker image build \
  --build-arg VCS_REF=$(git rev-parse — short HEAD) \
  --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
  --build-arg VERSION=$(cat VERSION) \
  -t $IMAGE_NAME .
